### PR TITLE
Update continuous-deployment-to-kubernetes.md

### PR DESCRIPTION
**Pull request by Nadine2016**

### CODE REVIEW

**Comment by l2fprod** [comment]
thank you. will be included in our next drop.

**Comment by fsgro** [comment]
@l2fprod when is plannet the next drop?

**Comment by l2fprod** [comment]
@fsgro the drop containing those changes already happened

**Comment by fsgro** [comment]
@l2fprod I'm don't see the tutorial with the chages made in [https://github.com/IBM-Bluemix-Docs/tutorials/pull/27/commits/fea64527cecc3dd8fae41cc87895b9f0ee414305](url)

**Comment by l2fprod** [comment]
@fsgro 

the changes in this PR are visible in https://cloud.ibm.com/docs/tutorials?topic=solution-tutorials-continuous-deployment-to-kubernetes#continuous-deployment-to-kubernetes

they came in with https://github.com/IBM-Bluemix-Docs/tutorials/commit/ab551f4a7bb192c06d4c42faace936d909fc74bb

**Comment by fsgro** [comment]
Thanks @l2fprod
I redirected the user to cloud.ibm.com waiting for the redirection of console.ibm.com to cloud.ibm.com

**Pull request closed without merging**
